# Generated by Django 4.2.4 on 2025-04-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('todos_clientes', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('data_inicio_envio', models.DateTimeField(blank=True, null=True)),
                ('data_fim_envio', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_envios', models.IntegerField(default=0)),
                ('total_aberturas', models.IntegerField(default=0)),
                ('total_cliques', models.IntegerField(default=0)),
                ('total_respostas', models.IntegerField(default=0)),
                ('taxa_abertura', models.FloatField(default=0)),
                ('taxa_clique', models.FloatField(default=0)),
                ('taxa_resposta', models.FloatField(default=0)),
                ('data_geracao', models.DateTimeField(auto_now=True)),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='marketing.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('clientes', models.ManyToManyField(related_name='grupos', to='marketing.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Envio'), ('enviado', 'Enviado'), ('falha', 'Falha no Envio'), ('aberto', 'Aberto'), ('clicado', 'Clicado'), ('respondido', 'Respondido')], default='aguardando', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, null=True)),
                ('data_clique', models.DateTimeField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='campanhas', to='marketing.grupocliente'),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='marketing.campanha')),
            ],
        ),
    ]
